--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/libPiggyUpdateChecker
build-by-default: true
branches:
- master
projects:
  libPiggyUpdateChecker:
    path: ""
    model: virion
    type: library
...
