name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run PHPStan
        uses: paroxity/pmmp-phpstan-action@4.2.0
        with:
          phpstan-config: phpstan.neon.dist
